#!/bin/bash
ENVIRONMENT=$1
NEWPLATFORMNAME=$2

PLATFORMNAME="$ENVIRONMENT-demo*"
i=local.drupalcamp-mtl15.sfl
if drush site-alias --format=csv --fields=root @${i} | grep -q "platforms/${PLATFORMNAME}" ; then
 echo "######### MIGRATING ${i} #####"
 ./migrate.drush ${i} $NEWPLATFORMNAME
fi